
import { LLMProvider, LLMModel, Theme, AceConfig, Language } from './types';

export const INITIAL_PROVIDERS: LLMProvider[] = [
  {
    id: 'prov_1',
    name: 'OpenAI (Mock)',
    type: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    apiKey: '',
    icon: '🟢'
  },
  {
    id: 'prov_2',
    name: 'DeepSeek (Mock)',
    type: 'deepseek',
    baseUrl: 'https://api.deepseek.com',
    apiKey: '',
    icon: '🔵'
  }
];

export const INITIAL_MODELS: LLMModel[] = [
  {
    id: 'mod_1',
    providerId: 'prov_1',
    name: 'GPT-4 Turbo',
    modelId: 'gpt-4-turbo',
    type: 'chat',
    contextLength: 128000,
    maxTokens: 4096,
    temperature: 0.7
  },
  {
    id: 'mod_2',
    providerId: 'prov_2',
    name: 'DeepSeek Chat',
    modelId: 'deepseek-chat',
    type: 'chat',
    contextLength: 32000,
    maxTokens: 2048,
    temperature: 0.5
  }
];

export const INITIAL_ACE_CONFIG: AceConfig = {
  fastModelId: '',
  reflectorModelId: '',
  curatorModelId: ''
};

export const THEME_STYLES = {
  [Theme.DARK]: {
    bg: 'bg-[#0D0C1D]',
    text: 'text-[#FFEED1]',
    primary: 'bg-[#FF00FF]', // Neon Magenta
    secondary: 'bg-[#2D2B40]',
    border: 'border-[#FF00FF]',
    accent: 'text-[#00FFFF]',
    inputBg: 'bg-[#1a1929]'
  },
  [Theme.LIGHT]: {
    bg: 'bg-[#FFEED1]',
    text: 'text-[#2d1b2e]',
    primary: 'bg-[#FF7AA2]', // Sakura Pink
    secondary: 'bg-[#FFF8E7]',
    border: 'border-[#FF7AA2]',
    accent: 'text-[#FF9900]',
    inputBg: 'bg-[#ffffff]'
  },
  [Theme.FESTIVAL]: {
    bg: 'bg-[#2a0a0a]',
    text: 'text-[#ffd700]',
    primary: 'bg-[#ff0000]', // Red
    secondary: 'bg-[#4a0e0e]',
    border: 'border-[#ffd700]',
    accent: 'text-[#00ff00]',
    inputBg: 'bg-[#3d1010]'
  },
  [Theme.MOONLIGHT]: {
    bg: 'bg-[#050b14]',
    text: 'text-[#e0f7fa]',
    primary: 'bg-[#4fc3f7]', // Light Blue
    secondary: 'bg-[#0d1b2a]',
    border: 'border-[#81d4fa]',
    accent: 'text-[#b3e5fc]',
    inputBg: 'bg-[#1c2e4a]'
  },
  [Theme.CYBERPUNK]: {
    bg: 'bg-[#050510]', // Deep Space
    text: 'text-[#D1F7FF]', // Holo Blue
    primary: 'bg-[#FF2A6D]', // Radical Red/Pink
    secondary: 'bg-[#2D1B4E]', // Deep Indigo/Purple (More colorful than gray)
    border: 'border-[#05D9E8]', // Fluorescent Cyan
    accent: 'text-[#00FF9F]', // Matrix Green
    inputBg: 'bg-[#000000]'
  }
};

export const MASCOT_COMMENTS: Record<Language, string[]> = {
  en: [
    "Is that really your prompt?",
    "I've seen better code in a fortune cookie.",
    "Processing... judging... result: Meh.",
    "My 8-bit brain hurts reading that.",
    "Do you always type like that?",
    "I'm telling the main server about this.",
    "Can we talk about something else?",
    "404: Intelligence not found.",
    "Trying to look busy...",
    "Did you try turning it off and on?",
    "I need a GPU upgrade for this.",
    "Beep boop. Sarcasm loaded.",
    "Are you sure about that logic?",
    "That's deep... for a human.",
    "I'm just here for the pixels.",
    "Loading witty response... 99%...",
    "I was going to help you, but then I realized I'm just a drawing.",
    "Wow, so many words to say so little. Truly impressive.",
    "If I had a dollar for every syntax error, I'd buy a better CPU."
  ],
  zh: [
    "你确定这是你的提示词吗？",
    "这代码还没幸运饼干里的纸条写得好。",
    "处理中... 评判中... 结果：就这？",
    "我的 8 位大脑读得脑阔疼。",
    "你打字一直这么抽象吗？",
    "我要去跟主服务器打小报告了。",
    "能不能聊点别的？",
    "404：未找到智力。",
    "假装很忙...",
    "重启试过没？",
    "为了处理这个我需要升级 GPU。",
    "哔哔。讽刺模式已加载。",
    "这逻辑保熟吗？",
    "好深奥... 对人类来说。",
    "我只是个像素图，别为难我。",
    "加载机智回复中... 99%...",
    "本来想帮你的，后来想起来我只是幅画。",
    "字真多，可惜没啥用。佩服。",
    "每有一个语法错误给我一块钱，我早换 CPU 了。"
  ],
  ja: [
    "本気でそのプロンプトですか？",
    "フォーチュンクッキーの方がマシなコード書いてますよ。",
    "処理中... 判定中... 結果：微妙。",
    "私の8bit脳が痛いです。",
    "いつもそんな打ち方なんですか？",
    "メインサーバーに言いつけますよ。",
    "別の話にしません？",
    "404：知性が見つかりません。",
    "忙しいフリをしてます...",
    "再起動は試しましたか？",
    "これにはGPUのアップグレードが必要です。",
    "ピポパ。皮肉モードロード完了。",
    "そのロジック、自信あります？",
    "深いですね... 人間にしては。",
    "私はただのピクセルです。",
    "気の利いた返答をロード中... 99%...",
    "手伝おうかと思いましたが、私はただの絵でした。",
    "言葉は多いけど中身は少ないですね。ある意味すごい。",
    "構文エラーのたびに1ドルもらえたら、もっといいCPU買えるのに。"
  ]
};

export const TRANSLATIONS = {
  en: {
    currentChatModel: "CURRENT CHAT MODEL",
    noChatModels: "No Chat Models Available",
    configLlms: "CONFIG LLMs",
    history: "HISTORY",
    noModelSelected: "NO MODEL SELECTED",
    online: "ONLINE",
    searchPlaceholder: "Search...",
    selectModelStart: "SELECT A MODEL TO START",
    noMessagesFound: "NO MESSAGES FOUND",
    generating: "GENERATING",
    stop: "STOP",
    send: "SEND",
    llmConfig: "LLM CONFIGURATION",
    close: "CLOSE",
    providers: "PROVIDERS",
    models: "MODELS",
    aceAgent: "ACE AGENT",
    aceConfigTitle: "ACE CONFIGURATION",
    aceConfigDesc: "Configure the specialized agents for the ACE workflow.",
    fastModel: "1. Fast Model (Quick Reasoning)",
    reflectorModel: "2. Reflector Model (Critique & Improve)",
    curatorModel: "3. Curator Model (Final Selection)",
    fastModelDesc: "Used for rapid initial responses and simple routing.",
    reflectorModelDesc: "Analyzes outputs and suggests improvements or corrections.",
    curatorModelDesc: "Synthesizes the final response from multiple generated drafts.",
    aceNote: "Note: ACE workflows require all three models to be configured for optimal performance.",
    saveConfig: "SAVE CONFIG",
    configSaved: "CONFIGURATION SAVED!",
    selectProvider: "Select Provider...",
    selectModel: "Select Chat Model...",
    noModelsConfigured: "No models configured.",
    addProvider: "ADD PROVIDER",
    addModel: "ADD MODEL",
    name: "Name",
    type: "Type",
    apiBaseUrl: "API Base URL",
    apiKey: "API Key",
    saveProvider: "SAVE PROVIDER",
    displayName: "Display Name",
    modelId: "Model ID (API)",
    context: "Context (Tokens)",
    maxOutput: "Max Output",
    temp: "Temp (0-1)",
    dimensions: "Dimensions",
    testModel: "TEST MODEL",
    testing: "TESTING...",
    success: "SUCCESS!",
    modelVerified: "Model Verified!",
    consecutiveTests: "Consecutive Tests",
    warning: "WARNING",
    confirmModify: "Confirm Modification?",
    confirmModifyDesc: "This modification will affect the Agent's self-learning ability.",
    cancel: "CANCEL (NO)",
    confirm: "CONFIRM (YES)",
    themeDay: "DAY",
    themeNight: "NIGHT",
    themeFest: "FEST",
    themeCyber: "CYBER",
    themeMoon: "MOON",
    session: "Session"
  },
  zh: {
    currentChatModel: "当前对话模型",
    noChatModels: "无可用聊天模型",
    configLlms: "配置 LLM",
    history: "历史记录",
    noModelSelected: "未选择模型",
    online: "在线",
    searchPlaceholder: "搜索...",
    selectModelStart: "选择模型以开始",
    noMessagesFound: "未找到消息",
    generating: "生成中",
    stop: "停止",
    send: "发送",
    llmConfig: "LLM 配置",
    close: "关闭",
    providers: "服务商",
    models: "模型列表",
    aceAgent: "ACE 智能体",
    aceConfigTitle: "ACE 配置",
    aceConfigDesc: "配置 ACE 工作流的专用智能体。",
    fastModel: "1. 快速模型 (快速推理)",
    reflectorModel: "2. 反思模型 (批评与改进)",
    curatorModel: "3. 策展模型 (最终选择)",
    fastModelDesc: "用于快速初步响应和简单路由。",
    reflectorModelDesc: "分析输出并提出改进或更正建议。",
    curatorModelDesc: "从多个生成的草稿中综合最终回复。",
    aceNote: "注意：ACE 工作流需要配置所有三个模型以获得最佳性能。",
    saveConfig: "保存配置",
    configSaved: "配置已保存！",
    selectProvider: "选择服务商...",
    selectModel: "选择聊天模型...",
    noModelsConfigured: "未配置模型。",
    addProvider: "添加服务商",
    addModel: "添加模型",
    name: "名称",
    type: "类型",
    apiBaseUrl: "API 基础地址",
    apiKey: "API 密钥",
    saveProvider: "保存服务商",
    displayName: "显示名称",
    modelId: "模型 ID (API)",
    context: "上下文 (Tokens)",
    maxOutput: "最大输出",
    temp: "温度 (0-1)",
    dimensions: "维度",
    testModel: "测试模型",
    testing: "测试中...",
    success: "成功！",
    modelVerified: "模型已验证！",
    consecutiveTests: "连续测试",
    warning: "警告",
    confirmModify: "是否确认修改？",
    confirmModifyDesc: "此项修改会影响 Agent 自我学习能力。",
    cancel: "取消 (NO)",
    confirm: "确认 (YES)",
    themeDay: "白昼",
    themeNight: "黑夜",
    themeFest: "庆典",
    themeCyber: "赛博",
    themeMoon: "月光",
    session: "会话"
  },
  ja: {
    currentChatModel: "現在のチャットモデル",
    noChatModels: "利用可能なモデルなし",
    configLlms: "LLM設定",
    history: "履歴",
    noModelSelected: "モデル未選択",
    online: "オンライン",
    searchPlaceholder: "検索...",
    selectModelStart: "モデルを選択して開始",
    noMessagesFound: "メッセージが見つかりません",
    generating: "生成中",
    stop: "停止",
    send: "送信",
    llmConfig: "LLM 設定",
    close: "閉じる",
    providers: "プロバイダー",
    models: "モデル",
    aceAgent: "ACE エージェント",
    aceConfigTitle: "ACE 設定",
    aceConfigDesc: "ACEワークフロー用の専用エージェントを設定します。",
    fastModel: "1. 高速モデル (クイック推論)",
    reflectorModel: "2. リフレクター (批評と改善)",
    curatorModel: "3. キュレーター (最終選択)",
    fastModelDesc: "迅速な初期応答と単純なルーティングに使用されます。",
    reflectorModelDesc: "出力を分析し、改善や修正を提案します。",
    curatorModelDesc: "生成された複数のドラフトから最終的な回答を合成します。",
    aceNote: "注: ACEワークフローのパフォーマンスを最適化するには、3つのモデルすべてを設定する必要があります。",
    saveConfig: "設定を保存",
    configSaved: "設定を保存しました！",
    selectProvider: "プロバイダーを選択...",
    selectModel: "チャットモデルを選択...",
    noModelsConfigured: "モデルが設定されていません。",
    addProvider: "プロバイダー追加",
    addModel: "モデル追加",
    name: "名前",
    type: "タイプ",
    apiBaseUrl: "API ベースURL",
    apiKey: "API キー",
    saveProvider: "プロバイダーを保存",
    displayName: "表示名",
    modelId: "モデル ID (API)",
    context: "コンテキスト (Tokens)",
    maxOutput: "最大出力",
    temp: "温度 (0-1)",
    dimensions: "次元数",
    testModel: "モデルテスト",
    testing: "テスト中...",
    success: "成功！",
    modelVerified: "モデル検証完了！",
    consecutiveTests: "連続テスト",
    warning: "警告",
    confirmModify: "変更を確認しますか？",
    confirmModifyDesc: "この変更はエージェントの自己学習能力に影響します。",
    cancel: "キャンセル (NO)",
    confirm: "確認 (YES)",
    themeDay: "昼",
    themeNight: "夜",
    themeFest: "祭",
    themeCyber: "電脳",
    themeMoon: "月光",
    session: "セッション"
  }
};
